# Generated by Django 6.0.2 on 2026-03-03 13:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='achieved_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='score',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='gamescore',
            index=models.Index(fields=['-score', '-achieved_at'], name='leaderboard_score_862305_idx'),
        ),
    ]
